#
DEVICE_FOLDER := device/Micromax/AQ5001

# inherit from the proprietary version
-include vendor/Micromax/AQ5001/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := AQ5001
##TARGET_NO_KERNEL := true

# Platform
TARGET_BOARD_PLATFORM := mt6582
TARGET_BOARD_PLATFORM_GPU := mali-400mp

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
#COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60 -DQCOM_HARDWARE
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true

#
BOARD_KERNEL_CMDLINE :=  androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x04000000 --tags_offset 0x00000100 --mtk 1
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_CUSTOM_BOOTIMG := true
BOARD_CUSTOM_MKBOOTIMG := mtkbootimg
BOARD_CUSTOM_BOOTIMG_MK := device/Micromax/AQ5001/mtk/bootimg.mk
#BOARD_MKBOOTIMG_ARGS := --mtk 1

# Custom recovery
##BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
TARGET_PREBUILT_KERNEL := device/Micromax/AQ5001/prebuilt/kernel
#TARGET_RECOVERY_INITRC := $(DEVICE_FOLDER)/init.rc
TARGET_RECOVERY_FSTAB := $(DEVICE_FOLDER)/twrp.fstab
#BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_FOLDER)/MTKbootimg.mk
#TARGET_RECOVERY_UEVENTD := $(DEVICE_FOLDER)/ueventd.rc
#
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_NTFS_3G := true
BOARD_TOUCH_RECOVERY := true
TW_DEFAULT_LANGUAGE := ru
TW_DEVICE_VERSION := by mehanik6
#
#TW_FORCE_CPUINFO_FOR_DEVICE_ID := true
#TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

# TWRP
##HAVE_SELINUX := true
#DEVICE_RESOLUTION := 600x1024
TW_THEME := portrait_hdpi
#TARGET_SCREEN_WIDTH := 600
#TARGET_SCREEN_HEIGHT := 1024
#RECOVERY_TOUCHSCREEN_SWAP_XY := true
#RECOVERY_TOUCHSCREEN_FLIP_Y := true
#
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
RECOVERY_GRAPHICS_USE_LINELENGTH := true
#TW_BOARD_CUSTOM_GRAPHICS := ../../../device/Micromax/AQ5001/graphics_5.1-mod.c
#
TW_DEFAULT_EXTERNAL_STORAGE := true
RECOVERY_SDCARD_ON_DATA := true
#
TW_NO_REBOOT_BOOTLOADER := true
#TW_NO_EXFAT := true
#TW_NO_EXFAT_FUSE := true
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp

# USB Mounting
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file

# Logging
#TWRP_EVENT_LOGGING := true
